name: LTSpice Installer
on: [push, pull_request]
jobs:
  Install-LTSpice:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Download LTSpice x64 installer
        run: curl -O https://ltspice.analog.com/software/LTspice64.exe
      - name: Execute LTSpice x64 installer
        run: |
          echo %cd%
          dir
          dir ..
          dir ..\..
          dir ..\..\..
          dir ..\..\..\..
      - run: echo "ğŸ This job's status is ${{ job.status }}."
